name: environment 

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9 
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - dash
  - plotly
  - jupyter
  - jupyter-dash
  - pip
  - pip:
    - jupyterlab-dash
